// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFf5BR60vl0Ikj5qHBxa6Amt6SEDfZ5G8',
    appId: '1:281742733501:web:6e54f18d401903295807d4',
    messagingSenderId: '281742733501',
    projectId: 'banksystem-9b053',
    authDomain: 'banksystem-9b053.firebaseapp.com',
    storageBucket: 'banksystem-9b053.appspot.com',
    measurementId: 'G-ZJMJW9V2DK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhV40FkYmBQ0uhEwvRwBJjjEArS7yS0n4',
    appId: '1:281742733501:android:8dcd0c0f699ebfe15807d4',
    messagingSenderId: '281742733501',
    projectId: 'banksystem-9b053',
    storageBucket: 'banksystem-9b053.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBOoF9Sxfw6IdnejZvVXvsfjdYFwB8ayC8',
    appId: '1:281742733501:ios:f96fa71fa1b0be2f5807d4',
    messagingSenderId: '281742733501',
    projectId: 'banksystem-9b053',
    storageBucket: 'banksystem-9b053.appspot.com',
    iosClientId: '281742733501-4vjdor3u6o8ftg1u45qj7rffu175nbak.apps.googleusercontent.com',
    iosBundleId: 'com.example.banksystem',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBOoF9Sxfw6IdnejZvVXvsfjdYFwB8ayC8',
    appId: '1:281742733501:ios:f96fa71fa1b0be2f5807d4',
    messagingSenderId: '281742733501',
    projectId: 'banksystem-9b053',
    storageBucket: 'banksystem-9b053.appspot.com',
    iosClientId: '281742733501-4vjdor3u6o8ftg1u45qj7rffu175nbak.apps.googleusercontent.com',
    iosBundleId: 'com.example.banksystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBFf5BR60vl0Ikj5qHBxa6Amt6SEDfZ5G8',
    appId: '1:281742733501:web:47c4af9db539efdd5807d4',
    messagingSenderId: '281742733501',
    projectId: 'banksystem-9b053',
    authDomain: 'banksystem-9b053.firebaseapp.com',
    storageBucket: 'banksystem-9b053.appspot.com',
    measurementId: 'G-TV8DVYEB5T',
  );
}
